export const USER_TYPE = "USER_TYPE"
export const SET_ID = "SET_ID"
export const ADD_EVENTS = "ADD_EVENTS"
export const GET_EVENTS = "GET_EVENTS"
export const DELETE_EVENT = "DELETE_EVENT"
export const UPDATE_EVENT = "UPDATE_EVENT"
export const EVENTBYID = "EVENTBYID"

export const ADD_EVENTS_SOCIETY = "ADD_EVENTS_SOCIETY"
export const GET_EVENTS_SOCIETY = "GET_EVENTS_SOCIETY"
export const DELETE_EVENT_SOCIETY = "DELETE_EVENT_SOCIETY"
export const UPDATE_EVENT_SOCIETY = "UPDATE_EVENT_SOCIETY"




export const SEARCH_BAR = "SEARCH_BAR"
export const PARTICIPATED_EVENTS = "PARTICIPATED_EVENTS"

export const ADD_NEWS = "ADD_NEWS"
export const GET_NEWS = "GET_NEWS"
export const DELETE_NEWS = "DELETE_NEWS"
export const UPDATE_NEWS = "UPDATE_NEWS"