export const USER_TYPE = "USER_TYPE"
export const SET_ID = "SET_ID"
export const ADD_EVENTS = "ADD_EVENTS"
export const GET_EVENTS = "GET_EVENTS"
export const DELETE_EVENT = "DELETE_EVENT"
export const UPDATE_EVENT = "UPDATE_EVENT"
export const SEARCH_BAR = "SEARCH_BAR"
export const PARTICIPATED_EVENTS = "PARTICIPATED_EVENTS"